# Use the latest version of ubuntu
FROM ubuntu:latest

# Uptade APT package lists
RUN apt-get uptade

# Upgrade installed software
RUN apt-get upgrade -y

# Print "Hello, World"
CMD echo "Hello, World"